name: Build binaries
run-name: ${{ github.actor }} is building binaries
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Package Application
              uses: JackMcKew/pyinstaller-action-windows@main
              with:
                  path: src
            - uses: actions/upload-artifact@v3
              with:
                  name: ${{ github.repository }}
                  path: src/dist/windows
