name: Build binaries
run-name: ${{ github.actor }} is building binaries
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        permissions: write-all
        runs-on: windows-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Setup python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - run: pip install pyinstaller
            - run: pip install -r requirements.txt
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  # body: |
                  #     Changes in this Release
                  #     - First Change
                  #     - Second Change
                  draft: false
                  prerelease: false
            - name: Build artifacts
              run: pyinstaller -F latex_template_to_vscode_snippet.py
            - name: Upload windows artifact
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./dist/latex_template_to_vscode_snippet
                  asset_name: latex_template_to_vscode_snippet
                  asset_content_type: application/octet-stream
